environment: beta

urls:
  beta: "https://beta.digitathya.com/admin/login"
  uat: "https://uat.digitathya.com/admin/login"
  production: "https://digitathya.com/admin/login"

browser: chrome

access_code: "2560"

users:

  # Default account (Sequential Execution)
  superadmin:
    username: "loadtesting_superadmin2@mailinator.com"
    password: "Password@123"

  manufacturer:
    username: "manufacturer@test.com"
    password: "Password123"

# =====================================================
# Automation Accounts (Parallel Execution)
# One account per xdist worker
# =====================================================
automation_users:

  - username: "loadtesting_superadmin2@mailinator.com"
    password: "Password@123"

  - username: "superadmin691434bb6692f@mailinator.com"
    password: "Password@123"

  - username: "superadmin691434bb76bc2@mailinator.com"
    password: "Password@123"

  - username: "superadmin691434bb86db8@mailinator.com"
    password: "Password@123"

  - username: "superadmin691434bb97735@mailinator.com"
    password: "Password@123"

  - username: "superadmin691434bba7839@mailinator.com"
    password: "Password@123"

timeouts:
  implicit_wait: 10
  explicit_wait: 20
  page_load_timeout: 60

execution:
  headless: false
  maximize_window: true

reports:
  html: "reports/html"
  screenshots: "reports/screenshots"
  logs: "reports/logs"

ulaa:
  path: "C:/Program Files/Zoho/Ulaa/Application/ulaa.exe"
