[common info]
access_code = 2560
baseURL = https://devalpha.digitathya.com/
username = manufacturer_retail@mailinator.com
password =Admin@123

#QAPrit@mailinator.com
#Testing@123

#manufacturer_691409ab52b58@mailinator.com
#Password@123

#black@mailinator.com
#Asdf@123

#manufacturer_retail@mailinator.com
#Admin@123
#https://devalpha.digitathya.com/

#https://beta.digitathya.com/admin/login

