[common info]
access_code = 2560
baseURL = https://beta.digitathya.com/admin/login
username = black@mailinator.com
password =Asdf@123

#QAPrit@mailinator.com
#Testing@123

#manufacturer_691409ab52b58@mailinator.com
#Password@123

#black@mailinator.com
#Asdf@123